apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: application-ucraft-app
spec:
  domains:
    - application.ucraft.app
  
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: docusaurus-ucraft-app
spec:
  domains:
    - docusaurus.ucraft.app