---
name: Build and Push Laravel Image to Google Cloud Platform
on: 
  push: 
    branches:
    - main
    paths:
    - laravel-app/**
  pull_request:
    branches:
    - main
    paths:
    - laravel-app/**

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./laravel-app
    env:
      IMAGE_NAME: laravel-app
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME:$GIT_TAG
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME:latest
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME:$GIT_TAG
