---
name: Build and Push Laravel Image to Google Cloud Platform
on: 
  push: 
    branches:
    - main
    paths:
    - ucraft-app/**
  pull_request:
    branches:
    - main
    paths:
    - ucraft-app/**

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ucraft-app
    env:
      IMAGE_NAME_1: laravel-app
      IMAGE_NAME_2: docusaurus-app
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker Image
      run: |-
        docker build -t $IMAGE_NAME_1:latest ./laravel-app/.
        docker build -t $IMAGE_NAME_2:latest ./docusaurus-app/.


    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ../scripts/git_update.sh -v patch

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME_1:latest gcr.io/$PROJECT_ID/$IMAGE_NAME_1:latest
        docker tag $IMAGE_NAME_1:latest gcr.io/$PROJECT_ID/$IMAGE_NAME_1:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME_1:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME_1:$GIT_TAG
        docker tag $IMAGE_NAME_2:latest gcr.io/$PROJECT_ID/$IMAGE_NAME_2:latest
        docker tag $IMAGE_NAME_2:latest gcr.io/$PROJECT_ID/$IMAGE_NAME_2:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME_2:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME_2:$GIT_TAG        

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME_1:latest europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_1:latest
        docker tag $IMAGE_NAME_1:latest europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_1:$GIT_TAG
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_1:latest
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_1:$GIT_TAG
        docker tag $IMAGE_NAME_2:latest europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_2:latest
        docker tag $IMAGE_NAME_2:latest europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_2:$GIT_TAG
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_2:latest
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/gar-eu-repo/$IMAGE_NAME_2:$GIT_TAG

    - name: Prep and Deploy to GKE
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials primary --zone europe-west3-a --project ${{ secrets.GCP_PROJECT_ID }}


    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f ../k8s/pv_pvc.yaml -f ../k8s/node_port.yaml -f ../k8s/deployment.yaml -f ../k8s/managed_certificate.yaml -f ../k8s/ingress.yaml